package query

const (
	testTableUsers   = "users"
	testColName      = "name"
	testColAge       = "age"
	testColScore     = "score"
	testColUserID    = "user_id"
	testColID        = "id"
	testColKey       = "key"
	testFuncCount    = "count"
	testFuncMin      = "min"
	testFuncMax      = "max"
	testFuncAvg      = "avg"
	testFuncAbs      = "abs"
	testAggCountStar = "COUNT(*)"
	testAggAVG       = "AVG"
	testAggSumAge    = "SUM(age)"
	testAggAvgAge    = "AVG(age)"
	testAggMinAge    = "MIN(age)"
	testAggMaxAge    = "MAX(age)"
	testAggSumScore  = "SUM(score)"
	testAggAvgScore  = "AVG(score)"
	testAggMinScore  = "MIN(score)"
	testAggMaxScore  = "MAX(score)"
	testAliasDivZero = "div_zero"
	testAliasNegAge  = "neg_age"
	testNameAlice    = "alice"
	testNameBob      = "bob"
	testNameCharlie  = "charlie"
	testNameDiana    = "diana"
	testNameEve      = "eve"
)
